version: '3.7'

services:
  nest-server:
    container_name: nest-server
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/nest-typeorm
    ports:
      - '$PORT_SERVER:$PORT_SERVER'
    depends_on:
      - nest-db
    restart: always
    networks:
      - common_network

  nest-db:
    container_name: nest-db
    image: postgres
    env_file: .env
    volumes:
      - .docker/database/:/var/lib/postgresql/data
    ports:
      - '$PORT_DB:$PORT_DB'
    restart: always
    expose:
      - '$PORT_DB'
    networks:
      - common_network

  adminer:
    container_name: 'adminer-mysql'
    image: adminer
    env_file: .env
    ports:
      - '$PORT_ADMINER:$PORT_ADMINER'
    environment:
      ADMINER_DEFAULT_SERVER: nest-db
      ADMINER_DESIGN: 'lucas-sandery' # theme
    restart: always
    depends_on:
      - nest-db
    networks:
      - common_network
networks:
  common_network:
    driver: bridge
    name: common_network
    external: true
