version: '3.7'

services:
  typeorm-server:
    container_name: typeorm-server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT_SERVER
    volumes:
      - ./:/nest-typeorm
    ports:
      - '${PORT_SERVER}:${PORT_SERVER}'
    depends_on:
      - typeorm-db
    restart: always
    networks:
      - typeorm_network

  typeorm-db:
    container_name: typeorm-db
    image: postgres
    volumes:
      - ./.docker/database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PORT_DB
    ports:
      - '${PORT_DB}:${PORT_DB}'
    restart: always
    expose:
      - '${PORT_DB}'
    networks:
      - typeorm_network

  adminer:
    container_name: adminer-mysql
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: ${POSTGRES_HOST}
      ADMINER_DESIGN: 'lucas-sandery' # theme
    ports:
      - '${PORT_ADMINER}:${PORT_ADMINER}'
    restart: always
    depends_on:
      - typeorm-db
    networks:
      - typeorm_network

networks:
  typeorm_network:
    driver: bridge
    name: typeorm_network
    external: true
